---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-resources
  namespace: ${argo_cd_namespace}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchExpressions:
          - key: 'gperreymond/argocd-deployer-all'
            operator: In
            values:
              - 'true'
        values:
          targetRevision: '${clusterResources.targetRevision}'
          loadBalancerIP: '{{ index .metadata.labels "gperreymond/loadBalancer-ip" }}'
  template:
    metadata:
      name: '{{ .name }}-cluster-resources'
      namespace: ${argo_cd_namespace}
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: shared
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
      sources:
        - repoURL: 'https://github.com/gperreymond/k8s-bootstrap.git'
          targetRevision: '{{ .values.targetRevision }}'
          helm:
            releaseName: cluster-resources
            values: |
              metallb:
                loadBalancerIP: '{{ .values.loadBalancerIP }}'
            valueFiles:
              - $values/charts/remote-values/metallb/global.yaml
      destination:
        server: '{{ .server }}'
        namespace: 'default'
