apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: dev-local
servers: 1
agents: 3
network: k3d-dev-local
ports:
- port: '80:80'
  nodeFilters:
  - loadbalancer
- port: '443:443'
  nodeFilters:
  - loadbalancer
