services:

  load-balancer:
    image: 'traefik:v3.2.1'
    container_name: 'load-balancer'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      - "traefik.http.routers.api.entryPoints=traefik"
      - "traefik.http.routers.api.service=api@internal"
    volumes:
      - './configs/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro'
      - './configs/traefik/dynamic.yaml:/etc/traefik/dynamic.yaml:ro'
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - '80:80/tcp'
      - '443:443/tcp'
      - '8000:8000/tcp'
    networks:
      k8s-bootstrap:
        ipv4_address: '172.29.0.100'

networks:
  k8s-bootstrap:
    external: true
