services:

  controller-server:
    image: "rancher/k3s:${K3S_VERSION}"
    container_name: controller-server
    command: 'server --disable-helm-controller --disable=traefik --disable=servicelb --bind-address=172.29.0.10 --node-name=node-server --node-label="pool-server=true" --node-taint=pool-server=true:NoExecute'
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_TOKEN=${K3S_CONTROLLER_TOKEN:?err}
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - k3s_controller_server:/var/lib/rancher/k3s
    networks:
      k8s-bootstrap:
        ipv4_address: '172.29.0.10'
    ports:
      - 80:80
      - 443:443

  controller-agent:
    image: "rancher/k3s:${K3S_VERSION}"
    container_name: controller-agent
    command: 'agent --node-name=node-worker'
    depends_on:
      - 'controller-server'
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
      - K3S_URL=https://controller-server:6443
      - K3S_TOKEN=${K3S_CONTROLLER_TOKEN:?err}
    volumes:
      - k3s_controller_agent:/var/lib/rancher/k3s
    networks:
      k8s-bootstrap:
        ipv4_address: '172.29.0.20'

networks:
  k8s-bootstrap:
    external: true
  
volumes:
  k3s_controller_server: {}
  k3s_controller_agent: {}