services:

  edge-server:
    image: "rancher/k3s:${K3S_VERSION}"
    container_name: edge-server
    command: 'server --disable-helm-controller --disable=traefik --disable=servicelb --bind-address=172.39.0.10 --node-name=node-server --node-label="pool-server=true" --node-taint=pool-server=true:NoExecute'
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_TOKEN=${K3S_EDGE_TOKEN:?err}
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - k3s_edge_server:/var/lib/rancher/k3s
    networks:
      edge-network:
        ipv4_address: '172.39.0.10'

  edge-agent:
    image: "rancher/k3s:${K3S_VERSION}"
    container_name: edge-agent
    command: 'agent --node-name=node-worker'
    depends_on:
      - 'edge-server'
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
      - K3S_URL=https://edge-server:6443
      - K3S_TOKEN=${K3S_EDGE_TOKEN:?err}
    volumes:
      - k3s_edge_agent:/var/lib/rancher/k3s
    networks:
      edge-network:
        ipv4_address: '172.39.0.20'

networks:
  edge-network:
    ipam:
      driver: default
      config:
        - subnet: '172.39.0.0/16'
  
volumes:
  k3s_edge_server: {}
  k3s_edge_agent: {}