# https://taskfile.dev
version: '3'

vars:
  KUBERNETES_VERSION: '1.29.3'
  ARGO_CD_VERSION: '6.7.11'
  ARGO_EVENTS_VERSION: '2.4.4'
  ARGO_WORKFLOWS_VERSION: '0.41.1'

tasks:

  # ---------------
  # INTERNALS
  # ---------------
  helm-repo:
    internal: true
    sources:
      - $(helm env HELM_REPOSITORY_CACHE)/*index.yaml
    cmds:
      - helm repo add argo https://argoproj.github.io/argo-helm
      - helm repo update
  install-argo-cd:
    sources:
    - charts/argo-cd-{{.ARGO_CD_VERSION}}.tgz
    - values/argo-cd.yaml
  deps:
    - helm-repo
  cmds:
    - helm pull argo/argo-cd --version {{.ARGO_CD_VERSION}} --destination charts
    - helm upgrade argo-cd charts/argo-cd-{{.ARGO_CD_VERSION}}.tgz --install --namespace argo-system --values values/argo-cd.yaml
  install-argo-events:
    internal: true
    sources:
      - charts/argo-events-{{.ARGO_EVENTS_VERSION}}.tgz
      - values/argo-events.yaml
    deps:
      - helm-repo
    cmds:
      - helm pull argo/argo-events --version {{.ARGO_EVENTS_VERSION}} --destination charts
      - helm upgrade argo-events charts/argo-events-{{.ARGO_EVENTS_VERSION}}.tgz --install --namespace argo-system --values values/argo-events.yaml
  install-argo-workflows:
    internal: true
    sources:
      - charts/argo-workflows-{{.ARGO_WORKFLOWS_VERSION}}.tgz
      - values/argo-workflows.yaml
    deps:
      - helm-repo
    cmds:
      - helm pull argo/argo-workflows --version {{.ARGO_WORKFLOWS_VERSION}} --destination charts
      - helm upgrade argo-workflows charts/argo-workflows-{{.ARGO_WORKFLOWS_VERSION}}.tgz --install --namespace argo-system --values values/argo-workflows.yaml

  # ---------------
  # ALLOWED
  # ---------------
  cluster-destroy:
    ignore_error: true
    cmds:
      - k3d cluster stop dev-local
      - k3d cluster delete dev-local
      - docker network rm k3d-dev-local
  cluster-create:
    cmds:
      - docker network create k3d-dev-local
      - k3d cluster create --image rancher/k3s:v{{.KUBERNETES_VERSION}}-k3s1 --config cluster.yaml
      - kubectx k3d-dev-local
      - kubectl cluster-info --context k3d-dev-local
  cluster-prepare:
    cmds:
      - cmd: mkdir charts
        ignore_error: true
      - kubectx k3d-dev-local
      - cmd: kubectl create ns argo-system
        ignore_error: true
      - task: install-argo-cd
      - task: install-argo-events
      - task: install-argo-workflows
      - kubectl apply -f manifests/000-argo-cd-projects.yaml
      - kubectl apply -f manifests/010-cert-manager.yaml
      - kubectl apply -f manifests/011-traefik.yaml
      - kubectl apply -f manifests/012-argo-cd.yaml
      - kubectl apply -f manifests/013-argo-workflows.yaml
