# https://taskfile.dev
version: '3'

vars:
  KUBERNETES_VERSION: '1.29.3'

tasks:

  # ---------------
  # INTERNALS
  # ---------------

  terraform-exec:
    internal: true
    cmds:
      - terraform -chdir={{.APP_MODULE_PATH}} fmt
      - terraform -chdir={{.APP_MODULE_PATH}} {{.CLI_ARGS}}

  # ---------------
  # ALLOWED
  # ---------------

  controller-start:
    cmds:
      - cmd: mkdir -p kubeconfigs/controller
        ignore_error: true
      - docker compose --file=docker-compose.controller.yaml --env-file=.env up --detach

  controller-stop:
    cmds:
      - docker compose --file=docker-compose.controller.yaml --env-file=.env down

  controller-terraform:
    cmds:
      - task: terraform-exec
        vars:
          APP_MODULE_PATH: "terraform/k8s-controller"
