# https://taskfile.dev
version: '3'

vars:
  KUBERNETES_VERSION: '1.29.3'

tasks:

  # ---------------
  # INTERNALS
  # ---------------

  terraform-exec:
    internal: true
    cmds:
      - terraform -chdir={{.APP_MODULE_PATH}} fmt
      - terraform -chdir={{.APP_MODULE_PATH}} {{.CLI_ARGS}}

  # ---------------
  # ALLOWED
  # ---------------

  k3s-start:
    cmds:
      - docker compose --file=docker-compose.{{.CLI_ARGS}}.yaml --env-file=.env up --detach

  k3s-stop:
    cmds:
      - docker compose --file=docker-compose.{{.CLI_ARGS}}.yaml --env-file=.env down

  kubeconfigs:
    cmds:
      - cmd: mkdir -p .kubeconfigs
        ignore_error: true
      - docker cp controller-server:/output/kubeconfig.yaml .kubeconfigs/controller.yaml
      - docker cp edge-server:/output/kubeconfig.yaml .kubeconfigs/edge.yaml
      - sed -i 's/\bdefault\b/k3s-controller/g' .kubeconfigs/controller.yaml
      - sed -i 's/\bdefault\b/k3s-edge/g' .kubeconfigs/edge.yaml

  terraform-controller:
    cmds:
      - task: terraform-exec
        vars:
          APP_MODULE_PATH: "terraform/k8s-controller"
