###############################################################
# Networks
###############################################################
networks:

  devops:
    name: devops
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.224.0/24


###############################################################
# Include
# Merge all of the below compose files into one large compose at run time
###############################################################
include:
  - ${DOCKERDIR}/services/k8s-server/compose.yaml
  - ${DOCKERDIR}/services/k8s-worker/compose.yaml
