api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  traefik:
    address: ":8000"

providers:
  docker:
    exposedByDefault: false
  file:
    filename: "/etc/traefik/dynamic.yaml"
    watch: false

log:
  level: 'INFO'
