ports:
  traefik:
    expose:
      default: true
  websecure:
    expose:
      default: false

ingressRoute:
  dashboard:
    enabled: true

service:
  enabled: true
  single: true
  type: LoadBalancer
  annotations:
    metallb.universe.tf/address-pool: traefik-pool
  spec:
    externalTrafficPolicy: Local
