---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: edge
  namespace: ${argo_cd_namespace}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: All applications to deploy in each "edge" clusters
  sourceRepos:
    - '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
      name: '*'