---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: internal
  namespace: ${argo_cd_namespace}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: All applications to deploy in "controller" cluster only
  sourceRepos:
    - '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: kube-system
      server: https://kubernetes.default.svc
      name: in-cluster
