apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: traefik-pool
  namespace: kube-system
spec:
  addresses:
    - '{{ .Values.loadBalancerIP }}/32'

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: traefik
  namespace: kube-system
spec:
  ipAddressPools:
    - traefik-pool
