---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argo-system
spec:
  description: All infra applications
  sourceRepos:
    - '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: cert-manager
      server: https://kubernetes.default.svc
      name: in-cluster
    - namespace: argo-system
      server: https://kubernetes.default.svc
      name: in-cluster
    - namespace: kube-system
      server: https://kubernetes.default.svc
      name: in-cluster

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argo-system
spec:
  description: All monitoring for datacenter
  sourceRepos:
    - '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: argo-system
      server: https://kubernetes.default.svc
      name: in-cluster
    - namespace: kube-system
      server: https://kubernetes.default.svc
      name: in-cluster