---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argo-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: '7.3.9'
    helm:
      values: |-
        adminUser: admin
        adminPassword: changeme
        extraLabels:
          app: grafana
          domain: monitoring
        persistence:
          enabled: true
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
