---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argo-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: '25.19.1'
    helm:
      values: |-
        commonMetaLabels:
          app: prometheus
          domain: monitoring
        configmapReload:
          prometheus:
            resources:
              requests:
                cpu: 10m
                memory: 16Mi
              limits:
                memory: 64Mi
        server:
          retention: 6h
          retentionSize: 5GB
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              memory: 2Gi
        alertmanager:
          enabled: false
        prometheus-pushgateway:
          enabled: false
        kube-state-metrics:
          enabled: true
          customLabels:
            app: kube-state-metrics
            domain: monitoring
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi
        prometheus-node-exporter:
          enabled: true
          podLabels:
            app: node-exporter
            domain: monitoring
          resources:
            requests:
              cpu: 100m
              memory: 30Mi
            limits:
              memory: 50Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
