name: 'k8s-server'

services:

  k8s-server:
    container_name: 'k8s-server'
    image: "rancher/k3s:${K3S_VERSION:?err}"
    command: 'server --disable-helm-controller --disable=traefik --disable=servicelb --bind-address=172.16.224.10 --node-name=node-server --node-label="pool-server=true" --node-taint=pool-server=true:NoExecute'
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    env_file:
      - ${DOCKERDIR}/.env
    environment:
      - K3S_TOKEN=${K3S_TOKEN:?err}
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    volumes:
      - k3s_server:/var/lib/rancher/k3s
    networks:
      devops:
        ipv4_address: '172.16.224.10'

volumes:
  
  k3s_server: {}
